config/routes.rb
Rails.application.routes.draw do
  resources :status_updates
  resources :profiles
  devise_for :users
  #get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :first_name, :last_name, :picture, presence: true

  mount_uploader :picture, ProfilePictureUploader

  def full_name
    [first_name, last_name].compact.join(' ')
    #"#(first_name)#(last_name)"
  end
end

app/models/status_update.rb
class StatusUpdate < ApplicationRecord
  belongs_to :user
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_many :status_updates
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.profile
        @profile = current_user.profile
        @status_update = StatusUpdate.new
        @status_updates = StatusUpdate.order(created_at: :desc)
      else
        @profile = Profile.new
      end
    end
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    @profile.user_id = current_user
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :first_name, :last_name, :picture, :hobbies)
    end
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController
  before_action :set_status_update, only: [:show, :edit, :update, :destroy]

  # GET /status_updates
  # GET /status_updates.json
  def index
    @status_updates = StatusUpdate.all
  end

  # GET /status_updates/1
  # GET /status_updates/1.json
  def show
  end

  # GET /status_updates/new
  def new
    @status_update = StatusUpdate.new
  end

  # GET /status_updates/1/edit
  def edit
  end

  # POST /status_updates
  # POST /status_updates.json
  def create
    @status_update = StatusUpdate.new(status_update_params)

    respond_to do |format|
      if @status_update.save
        format.html { redirect_to @status_update, notice: 'Status update was successfully created.' }
        format.json { render :show, status: :created, location: @status_update }
      else
        format.html { render :new }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_updates/1
  # PATCH/PUT /status_updates/1.json
  def update
    respond_to do |format|
      if @status_update.update(status_update_params)
        format.html { redirect_to @status_update, notice: 'Status update was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_update }
      else
        format.html { render :edit }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_updates/1
  # DELETE /status_updates/1.json
  def destroy
    @status_update.destroy
    respond_to do |format|
      format.html { redirect_to status_updates_url, notice: 'Status update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_update
      @status_update = StatusUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_update_params
      params.require(:status_update).permit(:status, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/views/home/index.html.erb
<h1>Welcome to FaceFactory</h1>
<% if user_signed_in? %>
<% if current_user.profile %>
<div class="row">
  <div class="col-md-4">
    <% render 'status_updates/form' %>
    <% @status_updates.each do |status| %>
    <div class="card card-block">
      <p><% status.user.profile.full_name %></p>
      <p><% status.status %></p>
      <p>Posted on: <%=
      time_ago_in_words(status.created_at) %></p>
    <!--status update goes here -->
  </div>
</div>
<!--wall goes here -->
<% else %>
<%= render 'profiles/form' %>

<% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <div class="container">
  <a class="navbar-brand" href="/">FaceFactory</a>
  <ul class="nav navbar-nav pull-xs-right">
    <li class="nav-item <%= 'active' if current_page?(root_path) %>">"
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <% if user_signed_in? %>
    <% if current_user.profile %>
    <li class="nav-item" <%= 'active' if
    current_page?(profile_path(current_user.profile)) %>">"
        <%= link_to 'My profile',
        profile_path(current)user.profile), class:
        'nav-link' %>
      </li>
      <% end %>
        <li class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:
    'nav-link' %></li>
    <% end %>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facefactory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :picture %>
    <%= f.input :hobbies %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Picture</th>
      <th>Hobbies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.picture %></td>
        <td><%= profile.hobbies %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4">
<div class="card">
  <img class="card-img-top" src="<%= @profile.picture %>" alt="Card image cap" width="100%">
  <div class="card-block">
    <h4 class="card-title"><% @profile.full_name %></h4>
    <p class="card-text">Hobbies: <br><%= @profile.hobbies %></p>
    <% if current_user == @profile.user %>
    <% link_to 'Edit', edit_profile_path(@profile), class: "btn btn-primary btn-sm" %>
    <% end %>
  </div>
</div>
  </div>
</div>
<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @profile.picture %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @profile.hobbies %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/status_updates/_form.html.erb
<%= simple_form_for(@status_update) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :update %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/status_updates/edit.html.erb
<h1>Editing Status Update</h1>

<%= render 'form', status_update: @status_update %>

<%= link_to 'Show', @status_update %> |
<%= link_to 'Back', status_updates_path %>

app/views/status_updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Status Updates</h1>

<table>
  <thead>
    <tr>
      <th>Update</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_updates.each do |status_update| %>
      <tr>
        <td><%= status_update.update %></td>
        <td><%= status_update.user %></td>
        <td><%= link_to 'Show', status_update %></td>
        <td><%= link_to 'Edit', edit_status_update_path(status_update) %></td>
        <td><%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status Update', new_status_update_path %>

app/views/status_updates/new.html.erb
<h1>New Status Update</h1>

<%= render 'form', status_update: @status_update %>

<%= link_to 'Back', status_updates_path %>

app/views/status_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Update:</strong>
  <%= @status_update.update %>
</p>

<p>
  <strong>User:</strong>
  <%= @status_update.user %>
</p>

<%= link_to 'Edit', edit_status_update_path(@status_update) %> |
<%= link_to 'Back', status_updates_path %>